# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_lamellafix_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamellafix',
            name='length',
            field=models.CharField(blank=True, max_length=25, verbose_name="Lamella's length"),
        ),
    ]
