# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_auto_20181114_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamellafix',
            name='weight',
            field=models.CharField(default=1, help_text='Weight of item', max_length=6, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='lamellafix',
            name='lamella_width',
            field=models.CharField(choices=[('38', '38 mm'), ('53', '53 mm'), ('63', '63 mm'), ('68', '68 mm')], default=53, help_text='Lammelas width', max_length=6, verbose_name='width'),
        ),
    ]
