# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_auto_20181114_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phonesnumber',
        ),
        migrations.AddField(
            model_name='customer',
            name='salutation',
            field=models.CharField(choices=[('mrs', 'Mrs.'), ('mr', 'Mr.'), ('na', '(n/a)')], default=1, max_length=5, verbose_name='Salutation'),
            preserve_default=False,
        ),
    ]
