# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_auto_20181114_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='salutation',
        ),
    ]
