# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_remove_customer_salutation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(blank=True, max_length=1024, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='ZIP / Postal code'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(blank=True, max_length=1024, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='ZIP / Postal code'),
        ),
    ]
