# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 05:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import email_auth.models
import filer.fields.file
import shop.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post_office', '0006_attachment_mimetype'),
        ('email_auth', '0004_auto_20170411_1733'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filer', '0010_auto_20180414_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('transition_target', models.CharField(max_length=50, verbose_name='Event')),
                ('notify', shop.models.fields.ChoiceEnumField(verbose_name='Whom to notify')),
                ('mail_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_office.EmailTemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'verbose_name': 'Notification',
                'ordering': ['transition_target', 'recipient_id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_attachment', to='filer.File')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Customers',
                'verbose_name': 'Customer',
                'indexes': [],
            },
            bases=('email_auth.user',),
            managers=[
                ('objects', email_auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('post_office.email',),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
    ]
