# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamellafix',
            name='discont_scheme',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='myshop.Discount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='discont_scheme',
            field=models.TextField(blank=True, help_text='Type discont scheme: first- quantity? second- rebate in %. Example: 10:25 - 10 -quantity 25%', max_length=100, verbose_name='Discount schema'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_name',
            field=models.CharField(max_length=100, verbose_name='Discount name'),
        ),
    ]
